import * as React from 'react';
import * as typings from './edit-helper.type';
import './edit-helper.scss';
export default class EditHelper extends React.Component<typings.PropsDefine, typings.StateDefine> {
    static defaultProps: typings.PropsDefine;
    state: typings.StateDefine;
    static ObserveEditHelper: typeof EditHelper;
    private SelfComponent;
    private componentInfo;
    private selfInstance;
    private selfDomInstance;
    private sortable;
    private startDrag;
    private lastClientX;
    private lastClientY;
    componentWillReact(): void;
    componentWillMount(): void;
    componentDidMount(): void;
    componentWillUpdate(nextProps: typings.PropsDefine, nextState: typings.StateDefine): void;
    componentWillUnmount(): void;
    setDragableClassIfNeed(): void;
    setLayoutActive(): void;
    setDraggingClass(): void;
    setSelectStyle(nextState: typings.StateDefine): void;
    handleMouseOver(event: MouseEvent): void;
    outerMoveBoxToSelf(): void;
    setSelect(selected: boolean): void;
    handleClick(event: MouseEvent): void;
    handleMouseDown(event: MouseEvent): void;
    handleMouseMove(event: MouseEvent): void;
    handleMouseUp(event: MouseEvent): void;
    render(): React.ReactElement<any>;
}
